### ISSUE TITLE
Help regarding SNV input file 

### ISSUE THREAD

**Issue by urmeya** [Shamir-Lab/PRODIGY#2]
I am new to handling of genomics data. Please help me with understanding of the data in the SNV input file

The file `COAD_SNV.RData` provided in the repository has a matrix of data with gene names as rows, patient sample ids as columns and the values in the matrix are 0, 1 or 0.5. 

What do these values denote? 
If I want to obtain such SNV data for some cancer type like BRCA (from public databases like GDC/ through some R package/ some other way), what are the steps required to obtain the matrix that can be used as input for PRODIGY?

**Comment by galdinstag** [comment]
The values denote whether the gene is mutated (value of 1) or not (all other values) as denoted in the man. The classification of mutations can be done in multiple ways and the assignment is left to the user to decide.

In the new PRODIGY implementation, one can simply provide a list of mutated genes to analyze, which should be easier to use.

Gal
