### ISSUE TITLE
Example code throws error

### ISSUE THREAD

**Issue by night-changes** [Shamir-Lab/PRODIGY#5]
I am trying to run the PRODIGY using the example data and code given in the README file.
when I running the function of [**all_patients_scores = PRODIGY_cohort()**]
The code throws the following error:
**Error evaluating 'object' argument when selecting method for 'edges' function: Error evaluating 'x' argument when selecting method for 'convertIdentifiers' function: subscript out of bounds**

How can I handle this?
Thanks!

**Comment by galdinstag** [comment]
Can you please reinstall the package and try again? i refactored parts of the code and its running on my side.
Thanks
Gal
